### ISSUE TITLE
F-Droid integration

### ISSUE THREAD

**Issue by GETandSELECT** [nielsvanvelzen/tv-launcher#9]
Hi

Thank you very much for your work.

I fully understand https://github.com/nielsvanvelzen/tv-launcher/issues/8
Please also consider a F-Droid integration. F-Droid is a project we trust.

**Comment by nielsvanvelzen** [comment]
Publishing apps for televisions on F-Droid is a bit pointless as there are no F-Droid clients that work on the TV as far as I am aware. If someone still wants it on F-Droid I'm open for pull requests for the fastlane structure, I won't submit it myself to F-Droid because the last time I did that for another app was a pain to be honest.

**Comment by GETandSELECT** [comment]
> Publishing apps for televisions on F-Droid is a bit pointless as there are no F-Droid clients that work on the TV as far as I am aware.

Correct, but there is a workaround to use it as "system apps". It's working, but I agree the experience not good.

> If someone still wants it on F-Droid I'm open for pull requests for the fastlane structure, I won't submit it myself to F-Droid because the last time I did that for another app was a pain to be honest.

Fully understand

**Comment by bt4ibwem8** [comment]
It is not pointless because there are f-droid clients working fine. For example i use [Droid-ify](https://f-droid.org/en/packages/com.looker.droidify/) on ATV 11 for installing apps. This issue should be re-opened because it was not resolved.
